export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTOS_FAILED = 'FETCH_PHOTOS_FAILED';
export const ADD_PHOTO_TO_FAVOURITES = 'ADD_PHOTO_TO_FAVOURITES';
export const REMOVE_PHOTO_FROM_FAVOURITES = 'REMOVE_PHOTO_FROM_FAVOURITES';